### ISSUE TITLE
Bot crash before sending trapsheet.png

### ISSUE THREAD

**Issue by Heater711** [robscallsign/HypeMan#3]
![Immagine](https://user-images.githubusercontent.com/72864507/96191474-73355580-0f44-11eb-9454-36b238e1ca62.png)

**Comment by adamburrito** [comment]
Heater, did you ever get this resolved? I'm trying to help some dude in Italy get his working and he's having the same issues... Tried reinstalling python a hundred times, everything else appears to be working... but he gets the same crash and message when a trapsheet is created. I've never had this issue on my server.
